ROLE_KEYWORDS = {
    "Project Management Trainee": [
        "project management",
        "agile",
        "scrum",
        "jira",
        "stakeholders",
        "risk management",
        "scope",
        "timeline",
        "requirements",
        "status report",
        "communication",
        "planning",
        "coordination",
        "reporting"
    ],
    "Project Coordinator": [
        "project coordination",
        "project management",
        "timeline",
        "status report",
        "meeting",
        "follow up",
        "stakeholders",
        "documentation",
        "risk",
        "planning",
        "jira",
        "requirements"
    ],
    "Junior Project Manager": [
        "project management",
        "agile",
        "scrum",
        "risk management",
        "scope",
        "budget",
        "timeline",
        "stakeholders",
        "project plan",
        "status report",
        "communication",
        "requirements"
    ],
    "Business Analyst": [
        "business analysis",
        "requirements",
        "stakeholders",
        "documentation",
        "process improvement",
        "user stories",
        "use case",
        "workflow",
        "analysis",
        "reporting",
        "communication",
        "excel"
    ],
    "Product Manager Intern": [
        "product management",
        "roadmap",
        "user research",
        "market research",
        "requirements",
        "stakeholders",
        "features",
        "prioritization",
        "user stories",
        "analytics",
        "communication",
        "problem solving"
    ],
    "Front-End Developer": [
        "html",
        "css",
        "javascript",
        "react",
        "api",
        "responsive design",
        "ui",
        "ux",
        "figma",
        "bootstrap",
        "tailwind",
        "frontend",
        "web development",
        "github"
    ],
    "React Developer": [
        "react",
        "javascript",
        "jsx",
        "components",
        "props",
        "state",
        "api",
        "html",
        "css",
        "responsive design",
        "frontend",
        "vite",
        "github"
    ],
    "Web Developer": [
        "html",
        "css",
        "javascript",
        "php",
        "laravel",
        "react",
        "bootstrap",
        "mysql",
        "api",
        "web development",
        "responsive design",
        "github"
    ],
    "Full Stack Developer": [
        "frontend",
        "backend",
        "html",
        "css",
        "javascript",
        "react",
        "python",
        "flask",
        "api",
        "database",
        "mysql",
        "mongodb",
        "github"
    ],
    "UI/UX Designer": [
        "ui",
        "ux",
        "figma",
        "wireframe",
        "prototype",
        "user research",
        "design system",
        "usability",
        "interface",
        "user experience",
        "visual design",
        "user flow",
        "accessibility"
    ],
    "UX Researcher": [
        "user research",
        "interviews",
        "survey",
        "persona",
        "usability testing",
        "user journey",
        "user flow",
        "analysis",
        "insights",
        "prototype",
        "figma",
        "ux"
    ],
    "IT Specialist": [
        "network",
        "troubleshooting",
        "technical support",
        "linux",
        "windows",
        "database",
        "security",
        "hardware",
        "software",
        "system",
        "it support",
        "infrastructure"
    ],
    "Technical Support Specialist": [
        "technical support",
        "troubleshooting",
        "customer support",
        "hardware",
        "software",
        "windows",
        "network",
        "ticketing",
        "problem solving",
        "communication",
        "it support"
    ],
    "Network Engineer": [
        "network",
        "routing",
        "switching",
        "tcp/ip",
        "dns",
        "dhcp",
        "firewall",
        "lan",
        "wan",
        "security",
        "troubleshooting",
        "ccna"
    ],
    "Cybersecurity Analyst": [
        "cybersecurity",
        "security",
        "risk",
        "vulnerability",
        "threat",
        "incident response",
        "network security",
        "information security",
        "linux",
        "monitoring",
        "firewall",
        "siem"
    ],
    "Data Analyst": [
        "data analysis",
        "excel",
        "sql",
        "python",
        "pandas",
        "power bi",
        "dashboard",
        "visualization",
        "reporting",
        "statistics",
        "data cleaning"
    ],
    "AI Intern": [
        "python",
        "machine learning",
        "ai",
        "data",
        "model",
        "nlp",
        "computer vision",
        "deep learning",
        "pandas",
        "numpy",
        "opencv",
        "classification"
    ],
    "Software Engineer Intern": [
        "software engineering",
        "programming",
        "python",
        "java",
        "javascript",
        "oop",
        "data structures",
        "algorithms",
        "database",
        "api",
        "github",
        "problem solving"
    ],
    "QA Tester": [
        "testing",
        "qa",
        "test cases",
        "bug report",
        "manual testing",
        "automation testing",
        "quality assurance",
        "uat",
        "jira",
        "documentation",
        "regression testing"
    ],
    "Systems Analyst": [
        "systems analysis",
        "requirements",
        "documentation",
        "workflow",
        "business process",
        "use case",
        "stakeholders",
        "database",
        "technical analysis",
        "communication",
        "solution design"
    ]
}


def get_role_list():
    return list(ROLE_KEYWORDS.keys())


def get_keywords(target_role):
    return ROLE_KEYWORDS.get(target_role, [])
